####
# Create a  shared-directory to fulfill the following requirements:
# A parent directory must be called /shared
# A child directory called /shared/finance
# A child directory called /shared/engineering
# A user Alice must be part of a group called finance. Make sure that Alice’s home directory is set to /home/finance/alice.
# A user Bob must be part of a group called engineering. Make sure that Bob’s home directory is set to /home/engineering/bob.
# A user Clare must be part of a group called finance and engineering. Make sure Clare’s home directory is set to /home/finance/clare.
# A user Nancy must be _only_ able to read files created by engineering.
# Users from group finance must be able to read and write at /shared/finance directory
# Users from group engineering must be able to read and write at /shared/engineering directory 
# Users that are not part of these groups, cannot see any files. 
---
- name: Directory and User Management
  hosts: all
  become: true
  
  tasks:
    - name: "[ DIRECTORY ] - Create home directories"
      file:
        path: "{{ item }}"
        state: directory
      with_items:
        - /home
        - /home/finance
        - /home/engineering
      tags:
        - users
        - directories

    - name: "[ USERS ] - Create groups"
      group:
        name: "{{ item }}"
      with_items:
        - engineering
        - finance
      tags:
        - users

    - name: "[ USERS ] - Creates user Nancy"
      user:
        name: nancy
        state: present
        generate_ssh_key: yes
      tags:
        - users

    - name: "[ USERS ] - Creating users Alice, Bob, Clare"
      user:
        name: "{{ item.username }}"
        home: "{{ item.homedir }}"
        shell: /bin/bash
        groups: "{{ item.groups }}"
        append: yes
        state: present
        generate_ssh_key: yes
      with_items:
        - {username: "alice", homedir: "/home/finance/alice",   groups: 'finance'}
        - {username: "bob",   homedir: "/home/engineering/bob", groups: 'engineering'}
        - {username: "clare", homedir: "/home/finance/clare",   groups: "engineering"}
      tags:
        - users

    - name: "[ DIRECTORY ] - Create /shared"
      file:
        path: /shared
        state: directory
        mode: '0775'
      tags:
        - users
        - directories

    - name: "[ DIRECTORY ] - Create sub-directories"
      file:
        path: "{{ item.dir }}"
        mode: "{{ item.mode }}"
        owner: "{{ item.owner }}"
        group: "{{ item.group }}"
        state: directory
      with_items:
        - { dir: '/shared/finance', mode: '2770', owner: 'root', group: 'finance'}
        - { dir: '/shared/engineering', mode: '2770', owner: 'root', group: 'engineering'}
      tags:
        - users
        - directories

    - name: "[ USERS ] - Allow Nancy to read engineering files"
      acl: 
        path: /shared/engineering
        entity: nancy
        etype: user
        recursive: yes
        state: present
        permissions: rx
      tags:
        - users
