# Start the postgres service and ensure it starts on boot.
# Copy the postgres dump from https://batman.usersys.redhat.com/pub/postgres.dump to the local system 
# and restore this file into the database.
---
- name: Deploy Apache Webserver
  hosts: all
  vars:
    server_name: ''
    document_root: ''
    server_admin: 'root@localhost'
    apache_vhosts:
      - {servername: "{{ server_name }}", documentroot: "{{ document_root }}", serveradmin: "{{ server_admin }}"}
  tasks:
    
    - name: Check if server_name is set
      fail: 
        msg: "You must set the variable server_name"
      when: server_name == ''

    - name: Check if document_root is set
      fail:
        msg: "You must set the variable document_root"
      when: document_root == ''

    - name: Ensure Apache is installed
      package:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: Create Virtual Host Document Root
      file:
        path: /srv/site1/www
        group: root
        mode: '0755'
        owner: root
        state: directory

    - name: Copy Webpage to server
      get_url:
        url: http://batman.usersys.redhat.com/pub/index.html
        #dest: /srv/site1/www/
        dest: "{{ document_root }}"
        mode: '0755'
        owner: apache
        group: apache

    - name: Downloading Virtual Host Jinja2 Template
      get_url:
        url: http://batman.usersys.redhat.com/pub/vhost1.conf.j2
        dest: /tmp/vhost1.conf.j2
        mode: '0777'
        owner: root
        group: root

    - name: Create Virtual Host Configuration
      template:
        src: ./vhost1.conf.j2
        dest: /etc/httpd/conf.d/

    - name: Start/Enable Apache Service
      systemd:
        state: restarted
        name: httpd
        enabled: yes