#Deploy Apache webserver and make sure it meets the following requirements:
#Test if httpd is installed
#Test if server_name variable is provided as an argument
#Test if document_root variable is provided as an argument
#Creates Document Root directory
#Copies the webpage from http://people.redhat.com/tasander/index.html to the Document Root directory
#Download the virtual host configuration from http://people.redhat.com/tasander/vhost1.conf.j2 and deploy this as your Virtual Host configuration, accepting server_name, document_root, and server_admin as variables.
---
- name: Deploy Apache Webserver
  hosts: all
  vars:
    server_name: ''
    document_root: ''
    server_admin: 'root@localhost'
    webpage_download_url: "http://batman.usersys.redhat.com/pub/index.html"
    vhost_template: "./vhost1.conf.j2"
    vhost_conf: 'vhost1.conf'
    apache_vhosts:
      - {server_name: "{{ server_name }}", document_root: "{{ document_root }}", server_admin: "{{ server_admin }}"}
    required_variables:
      - document_root
      - server_name
      - webpage_download_url
      - vhost_template
  tasks:
        
    - name: "Check if required_variables is set"
      fail:
        msg: "You must set {{ item }}"
      when: "{{ item }} is defined and {{ item }}|length == 0" 
      with_items:
        - "{{ required_variables }}"

    - name: Ensure Apache is installed
      package:
        name: httpd
        state: present
      when: ansible_os_family == "RedHat"

    - name: Create Virtual Host Document Root
      file:
        path: "{{ document_root }}"
        group: root
        mode: '0755'
        owner: root
        state: directory

    - name: Copy Webpage to server
      get_url:
        url: "{{ webpage_download_url }}"
        dest: "{{ document_root }}"
        mode: '0755'
        owner: apache
        group: apache

    - name: Create Virtual Host Configuration
      template:
        src: "{{ vhost_template }}"
        dest: /etc/httpd/conf.d/{{ vhost_conf }}

    - name: Start/Enable Apache Service
      systemd:
        state: restarted
        name: httpd
        enabled: yes
