# Download the file “hosts” from http://batman.usersys.redhat.com/pub/hosts to /etc/hosts on the local system. 
# Make sure the checksum of the file matches with the XXXXXXXX
---
- name: Deploy hosts file on target
  hosts: ansible-target.usersys.redhat.com
  become: true
  remote_user: root
  tasks:

    - name: Download and Validate file
      get_url:
        url: http://batman.usersys.redhat.com/pub/hosts
        dest: /etc/hosts
        mode: '0644'
        owner: root
        group: root
        checksum: md5:"{{ hosts_md5 }}"